"""
Discovery Call Research Agent
==============================
Researches a prospect before a discovery call and generates
a structured one-pager briefing.

Usage:
    uv run python agent.py "John Smith" "Acme Corp"
    uv run python agent.py "Jane Doe" "TechStart Inc" --linkedin "https://linkedin.com/in/janedoe"
    uv run python agent.py "Jane Doe" "TechStart Inc" --email       # Email the report
    uv run python agent.py "Jane Doe" "TechStart Inc" --output pdf  # Save as PDF-ready markdown
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI
from ddgs import DDGS
from rich.console import Console
from rich.markdown import Markdown

load_dotenv()

console = Console()

RESEARCH_SYSTEM_PROMPT = """You are a pre-call research analyst for an AI automation agency.
Your job is to analyze raw search results about a prospect and their company, then produce
a structured intelligence briefing that helps prepare for a discovery call.

Focus on:
1. What the company does and who they serve
2. Company size, stage, and recent news/changes
3. The prospect's role and background
4. Pain points this type of business typically has that AI automation could solve
5. Specific automation opportunities based on their industry and operations
6. Conversation starters and rapport-building angles
7. Red flags or things to be careful about

Be specific and actionable. Frame insights through the lens of the "Three Ways AI Creates Profit":
- Get more customers (marketing, lead gen, outreach)
- Make each customer worth more (upselling, retention, experience)
- Cut costs (automate repetitive tasks, reduce errors, save time)
"""

BRIEFING_TEMPLATE = """# Discovery Call Briefing
**Prospect:** {name}
**Company:** {company}
**Date:** {date}
{linkedin_line}

---

{analysis}

---

## Suggested Opening
> "I came across {company} and was really interested in [SPECIFIC DETAIL]. I'd love to understand
> more about how your team handles [RELEVANT PROCESS] day-to-day."

---
*Generated by Discovery Research Agent | {date}*
"""


def search_web(query: str, max_results: int = 8) -> list[dict]:
    """Search the web using DuckDuckGo."""
    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=max_results))
            return results
    except Exception as e:
        console.print(f"[yellow]Search warning: {e}[/yellow]")
        return []


def research_prospect(name: str, company: str, linkedin_url: str | None = None) -> dict:
    """Run multiple search queries to gather prospect intelligence."""
    console.print("\n[bold blue]🔍 Researching prospect...[/bold blue]\n")

    searches = {
        "company_overview": f"{company} company about what they do",
        "company_news": f"{company} recent news 2025 2026",
        "prospect_profile": f"{name} {company}",
        "industry_trends": f"{company} industry AI automation trends",
        "company_tech": f"{company} technology stack tools software",
    }

    if linkedin_url:
        searches["linkedin"] = f"site:linkedin.com {name} {company}"

    all_results = {}
    for label, query in searches.items():
        console.print(f"  Searching: [dim]{query}[/dim]")
        results = search_web(query)
        all_results[label] = results

    return all_results


def generate_briefing(
    name: str,
    company: str,
    research_data: dict,
    linkedin_url: str | None,
    client: OpenAI,
    model: str,
) -> str:
    """Use OpenAI to analyze research data and generate the briefing."""
    console.print("\n[bold blue]🤖 Generating briefing...[/bold blue]\n")

    # Format research data for the prompt
    research_text = ""
    for category, results in research_data.items():
        research_text += f"\n### {category.replace('_', ' ').title()}\n"
        for r in results:
            research_text += f"- **{r.get('title', 'N/A')}**: {r.get('body', 'N/A')}\n"
            if r.get("href"):
                research_text += f"  Source: {r['href']}\n"

    user_prompt = f"""Research the following prospect and generate a comprehensive discovery call briefing.

**Prospect Name:** {name}
**Company:** {company}
**LinkedIn:** {linkedin_url or 'Not provided'}

## Raw Research Data
{research_text}

Generate a briefing with these sections:

## Company Overview
Brief summary of what the company does, who they serve, approximate size/stage.

## Prospect Background
What we know about {name}'s role, experience, and focus areas.

## Industry Context
Key trends, challenges, and opportunities in their industry related to AI/automation.

## Automation Opportunities (Top 3-5)
For each opportunity, specify:
- What process could be automated
- Which of the "Three Profit Levers" it addresses (more customers / higher value / cut costs)
- Estimated impact (time saved, revenue potential)
- Suggested approach

## Conversation Starters
3-5 specific, personalized questions or talking points based on the research.

## Competitive Intelligence
What competitors or similar companies are doing with AI/automation.

## Red Flags & Notes
Anything to be cautious about — recent layoffs, controversies, budget constraints, etc.

Be specific. Use actual details from the research, not generic filler."""

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": RESEARCH_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.3,
        max_tokens=3000,
    )

    return response.choices[0].message.content


def save_briefing(content: str, name: str, company: str) -> Path:
    """Save the briefing to a markdown file."""
    output_dir = Path(__file__).parent / "output"
    output_dir.mkdir(exist_ok=True)

    safe_name = f"{company.lower().replace(' ', '_')}_{name.lower().replace(' ', '_')}"
    date_str = datetime.now().strftime("%Y%m%d")
    filename = f"briefing_{safe_name}_{date_str}.md"

    filepath = output_dir / filename
    filepath.write_text(content)
    return filepath


def main():
    parser = argparse.ArgumentParser(description="Discovery Call Research Agent")
    parser.add_argument("name", help="Prospect's full name")
    parser.add_argument("company", help="Prospect's company name")
    parser.add_argument("--linkedin", help="Prospect's LinkedIn URL", default=None)
    parser.add_argument(
        "--output",
        choices=["terminal", "markdown", "both"],
        default="both",
        help="Output format (default: both)",
    )
    args = parser.parse_args()

    # Validate API key
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        console.print("[red]❌ OPENAI_API_KEY not set. Copy .env.example to .env and add your key.[/red]")
        sys.exit(1)

    client = OpenAI(api_key=api_key)
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

    console.print(f"\n[bold]📋 Discovery Call Research Agent[/bold]")
    console.print(f"   Prospect: {args.name}")
    console.print(f"   Company:  {args.company}")
    if args.linkedin:
        console.print(f"   LinkedIn: {args.linkedin}")
    console.print(f"   Model:    {model}")

    # Step 1: Research
    research_data = research_prospect(args.name, args.company, args.linkedin)

    total_results = sum(len(v) for v in research_data.values())
    if total_results == 0:
        console.print("[red]❌ No search results found. Check your internet connection.[/red]")
        sys.exit(1)

    console.print(f"  [green]✅ Found {total_results} search results across {len(research_data)} queries[/green]")

    # Step 2: Generate briefing
    analysis = generate_briefing(
        args.name, args.company, research_data, args.linkedin, client, model
    )

    linkedin_line = f"**LinkedIn:** {args.linkedin}" if args.linkedin else ""
    briefing = BRIEFING_TEMPLATE.format(
        name=args.name,
        company=args.company,
        date=datetime.now().strftime("%B %d, %Y"),
        linkedin_line=linkedin_line,
        analysis=analysis,
    )

    # Step 3: Output
    if args.output in ("terminal", "both"):
        console.print("\n")
        console.print(Markdown(briefing))

    if args.output in ("markdown", "both"):
        filepath = save_briefing(briefing, args.name, args.company)
        console.print(f"\n[green]✅ Briefing saved to: {filepath}[/green]")


if __name__ == "__main__":
    main()
